### ISSUE TITLE
running test page locally produces: net::ERR_CONTENT_DECODING_FAILED

### ISSUE THREAD

**Issue by evan-wehi** [Karasiq/scalajs-bootstrap#10]
Hello,

attempted to build the test example as per the instructions. The build completes (with many warnings) and server starts but doing a GET on the server produces a 161k binary file.

`GET http://localhost:9000/ net::ERR_CONTENT_DECODING_FAILED`

Here is the sbt output: https://gist.github.com/evan-wehi/1405907ab3dff6c10067ae86a0a5c13c

**Comment by Karasiq** [comment]
Looks like a gzip decompression issue.
Try to comment [compress directive](https://github.com/Karasiq/scalajs-bootstrap/blob/master/test/src/main/scala/com/karasiq/bootstrap/test/backend/BootstrapTestApp.scala#L23)

```scala
...
get {
        /* compressResponse() */ {
...
```

**Comment by evan-wehi** [comment]
Yes - that fixes it.
