### ISSUE TITLE
Readme Imports Don't Allow JQuery Use

### ISSUE THREAD

**Issue by cwfitzgerald** [Karasiq/scalajs-bootstrap#11]
I can't seem to figure out what combination of imports I need to have in order to pull in the proper implicits to let me do something like `$("#shortLinkModel").modal("blah")`

**Comment by Karasiq** [comment]
Use [BootstrapJQueryImplicits](https://github.com/Karasiq/scalajs-bootstrap/blob/d0be9d7cf8d0e9c33c8d8d02722f9443504ff667/jquery/src/main/scala/com/karasiq/bootstrap/jquery/BootstrapJQueryImplicits.scala#L13)
