### ISSUE TITLE
Popover code

### ISSUE THREAD

**Issue by gilbertbigras** [Karasiq/scalajs-bootstrap#13]
Not really an issue but cannot find an example to trigger a popover
The code starts with an element (on which I want to trigger a popover)
The following code produces nothing

_val anElement = e.element
anElement.attr("data-toggle","popover")
PopoverOptions(animation=false,container="body",html=true,trigger="hover",content="Hello")
Popover("Sometitle",anElement.asInstanceOf[org.scalajs.dom.raw.Element],TooltipPlacement.right)_

... _anElement.popover()_ does not work either

Thanks for any hint

**Comment by Karasiq** [comment]
```scala
jQuery(element).popover(options)
```
Should work
See https://github.com/Karasiq/scalajs-bootstrap/blob/master/library-v4/js/src/main/scala/com/karasiq/bootstrap4/popover/JSPopovers.scala
